info:
  title: 時雨的前端隨筆
  author: 時雨 Justin
  url: https://frontendnote.site
  keywords:
    - 時雨
    - 前端
    - react
    - javascript
    - next.js

defaults:
  favicon: /images/common/blog-logo.svg
  logo: /images/common/blog-logo.svg

colors:
  #Primary color
  primary: "#005080"

global:
  chinese:
    enable: true
    family: Noto Sans TC
    url: https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;500;700&display=swap
  english:
    enable: true
    family: Noto Sans
    url: https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700&display=swap
  google_analytics:
    enable: true
    id: G-WMGR1X63QG
  
home_banner:
  title: "時雨的前端隨筆"
  subtitle:
    text: ["分享前端、程式開發的學習筆記"]
    loop: false
  social_links:
    enable: true
    links:
      github: https://github.com/jjustin-35
      linkedin: https://www.linkedin.com/in/jjustin-chen
      fa-solid fa-envelope: mailto:jjusttin11@gmail.com

navbar: 
  links:
    Home: 
      path: /
      icon: fa-regular fa-house
    文章: 
      path: /article 
      icon: fa-regular fa-file-lines
      submenus: 
        前端筆記: /categories/frontend
        生活隨筆: /categories/life
        鐵人賽 2023: /categories/frontend/ironman-2023
    關於: 
      path: /about
      icon: fa-regular fa-user

